name: Coverage
on:
  pull_request_target:
    branches:
      - release
      - dev
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            package-manager: yarn
