name: Lint files, run unit and build tests
"on": push
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              yarn
              yarn lint
              yarn test
              yarn build
